### ISSUE TITLE
Solaire mode not properly enabled in emacsclient

### ISSUE THREAD

**Issue by zamlz** [hlissner/emacs-solaire-mode#46]
Hey So i'm not seeing `solaire-mode` properly enabled when I use it alongside an emacsclient setup. It does however work, when I change themes from the client. Because of this I figured that perhaps all I needed was to add `:after solaire-mode` in the `doom-themes` configuration.

**Comment by jeslie0** [comment]
As a temporary fix, you can add the following to you config file, replaceing doom-palenight with your chosen theme. 

`(add-hook 'server-after-make-frame-hook  '(lambda () (load-theme 'doom-palenight t)))`

This will fix your client, but it will cause the non-client emacs to be themeless.

**Comment by hlissner** [comment]
Can you expand on how you are activating solaire-mode? Or at the very least provide steps to reproduce the problem? This seems like a configuration issue.

**Comment by jeslie0** [comment]
My related setup is the following:

```
(use-package solaire-mode
  :defer t
  :custom
  (solaire-global-mode +1)
  )

(use-package doom-themes
  :defer t
  :hook (server-after-make-frame . (lambda () (load-theme
					       'doom-palenight t)))
  )
```
Using this, I get Solaire mode to work in emacsclient. If I just do the usual "load-theme", it doesn't get loaded properly.

**Comment by grszkthfr** [comment]
I have the same problem with emacsclient. Although, I don't get the provided work around working with the modus themes.

When I run emacs (not emacsclient) with same config it works as expected.

However, I can get the desired behavior by executing the `(use-package modus-themes [...])` by hand in a running session. As such, I also experimented with the `:after` keyword, with no success. 

FWIW, [my config](https://gitlab.com/grszkthfr/dotfiles/-/blob/master/emacs/.emacs.d/init.el#L624-644):

```emacs-lisp
(use-package modus-themes
  :bind(
        ("C-x M-t t" . modus-themes-toggle))
  :init
  ;; Add all your customizations prior to loading the themes
  (setq modus-themes-italic-constructs t
        modus-themes-bold-constructs t
        modus-themes-region '(bg-only no-extend)
        modus-themes-org-blocks 'tinted-background)

  ;; Load the theme files before enabling a theme
  (modus-themes-load-themes)

  :config
  ;; Load the theme of your choice:
  (modus-themes-load-vivendi))

(use-package solaire-mode
  :config
  (solaire-global-mode +1))
```

**Comment by jhncondix** [comment]
Same problem of solaire-mode not loading in emacsclient using emacs 28.1 with doom-gruvbox theme. So I followed suggestion and added:

(add-hook 'server-after-make-frame-hook '(lambda () (load-theme 'doom-gruvbox t)))

This worked to enable solaire-mode, but it messed up a bunch of font faces, turning all the grey comments in elisp files and in the scratch buffer into bright red, and the org-mode #+begin_quote mark up red. I did not want to start going through and figuring out what faces had been changed and changing them all by hand, so I just uninstalled.

But again, it worked fine when not running emacs in client mode.

**Comment by hlissner** [comment]
Sorry for taking so long to get to this. As of e8fcce7 this should be resolved. Thanks for bringing it to my attention!

**Comment by 45mg** [comment]
> Sorry for taking so long to get to this. As of [e8fcce7](https://github.com/hlissner/emacs-solaire-mode/commit/e8fcce77ea8ae47bcba4e4ea0596fed369c4f0cd) this should be resolved. Thanks for bringing it to my attention!

This doesn't fix the issue for me.

Also, I don't know where to bring this up, but -

> Same problem of solaire-mode not loading in emacsclient using emacs 28.1 with doom-gruvbox theme. So I followed suggestion and added:
> 
> (add-hook 'server-after-make-frame-hook '(lambda () (load-theme 'doom-gruvbox t)))

1) It's a little faster to use `enable-theme` here instead of `load-theme`.
2) For Doom users, the above will mess up `pdf-view-midnight-mode` due to [a hack](https://github.com/doomemacs/doomemacs/blob/da3d0687c5008edbbe5575ac1077798553549a6a/modules/tools/pdf/config.el#L65) in `:tools pdf` (images will get re-created every time you open a new client frame, without midnight-mode applied). You can get around this by disabling the hack -
```emacs-lisp
(after! pdf-tools (put 'pdf-view-midnight-colors 'custom-set nil))
```
